In [1]:

# Baseline MLP for MNIST dataset
import keras
from keras.datasets import mnist
import numpy as np
import math


Using TensorFlow backend.


In [8]:
def sigmoid (x):
    return 1/(1 + np.exp(-x))
def sigmoid_derivative(x):
    return x * (1 - x)
def loss(predicted_output,desired_output):
    return 1/2*(desired_output-predicted_output)**2

class NeuralNetwork() :
    def __init__ (self, inputLayerNeuronsNumber , hiddenLayerNeuronsNumber, outputLayerNeuronsNumber):
        self.inputLayerNeuronsNumber = inputLayerNeuronsNumber
        self.hiddenLayerNeuronsNumber = hiddenLayerNeuronsNumber
        self.outputLayerNeuronsNumber = outputLayerNeuronsNumber
        self.learning_rate = 0.1
        #He initialization
        self.hidden_weights = np.random.randn(hiddenLayerNeuronsNumber,inputLayerNeuronsNumber)*np.sqrt(2/inputLayerNeuronsNumber)
        self.hidden_bias = np.zeros([hiddenLayerNeuronsNumber,1])
        self.output_weights = np.random.randn(outputLayerNeuronsNumber,hiddenLayerNeuronsNumber)
        self.output_bias = np.zeros([outputLayerNeuronsNumber,1])
        self.loss = []
        
        
    def train(self, inputs, desired_output):
        
        hidden_layer_in = np.dot(self.hidden_weights, inputs) + self.hidden_bias
        hidden_layer_out = sigmoid(hidden_layer_in)
        
        output_layer_in = np.dot(self.output_weights, hidden_layer_out) + self.output_bias
        predicted_output = sigmoid(output_layer_in)
        
        error = desired_output - predicted_output
        d_predicted_output = error * sigmoid_derivative(predicted_output)
        
        error_hidden_layer = d_predicted_output.T.dot(self.output_weights)
        d_hidden_layer = error_hidden_layer.T * sigmoid_derivative(hidden_layer_out)
                
        self.output_weights += hidden_layer_out.dot(d_predicted_output.T).T * self.learning_rate
        self.output_bias += np.sum(d_predicted_output, axis=0, keepdims=True) * self.learning_rate
        
        self.hidden_weights += inputs.dot(d_hidden_layer.T).T * self.learning_rate
        self.hidden_bias += np.sum(d_hidden_layer, axis=0, keepdims=True) * self.learning_rate
        self.loss.append(loss(predicted_output,desired_output))
        
        
    def predict(self, inputs):
        #Forward Pass
        hidden_layer_in = np.dot(self.hidden_weights, inputs) + self.hidden_bias
        hidden_layer_out = sigmoid(hidden_layer_in)
        output_layer_in = np.dot(self.output_weights, hidden_layer_out) + self.output_bias
        predicted_output = sigmoid(output_layer_in)
        return predicted_output

In [32]:
import numpy as np
from mlxtend.data import loadlocal_mnist

#Importing dataset
X, y = loadlocal_mnist(images_path='./data/train-images.idx3-ubyte',labels_path='./data/train-labels.idx1-ubyte')

#Spliting dataset
num_train = 50000
num_test = 10000
X_train = X[:num_train, :]/255
y_train = np.zeros((num_train, 10))
y_train[np.arange(0, num_train) ,y[:num_train]] = 1  

X_test = X[num_train:, :]/255
y_test = np.zeros((num_test, 10))
y_test[np.arange(0, num_test) ,y[y.size - num_test:]] = 1

print("Training set shape : ",X_train.shape)
print("Test set shape : ",X_test.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Training set shape :  (50000, 784)
Test set shape :  (10000, 784)


In [12]:

nn=NeuralNetwork(784,350,10)

    
for i in range(X_train.shape[0]):
    inputs = np.array(X_train[i, :].reshape(-1,1))
    desired_output = np.array(y_train[i, :].reshape(-1,1))
    nn.train(inputs, desired_output)

loss at iteration :  999 [[2.55089656e-16]
 [1.49867487e-09]
 [1.00603335e-13]
 [1.86569303e-16]
 [2.11171138e-08]
 [1.30649735e-10]
 [2.04254433e-06]
 [4.33064287e-13]
 [4.43691995e-05]
 [5.19481048e-06]]
loss at iteration :  1999 [[2.79383541e-07]
 [2.64950463e-16]
 [3.47679790e-15]
 [1.39273116e-12]
 [6.91560933e-24]
 [8.77519710e-10]
 [5.67571921e-08]
 [1.04086380e-19]
 [4.87139501e-07]
 [1.26584981e-22]]
loss at iteration :  2999 [[3.78598747e-08]
 [1.51824603e-07]
 [1.82826755e-06]
 [1.18281469e-05]
 [2.01499123e-07]
 [6.66500708e-06]
 [5.95542055e-07]
 [4.67850187e-09]
 [6.10786559e-04]
 [2.50359740e-04]]
loss at iteration :  3999 [[5.31887381e-09]
 [8.97107833e-09]
 [1.78551000e-02]
 [1.04265514e-13]
 [4.20606410e-07]
 [1.40204847e-06]
 [3.01346689e-05]
 [5.76629406e-10]
 [4.19416283e-07]
 [1.69933129e-07]]
loss at iteration :  4999 [[2.41656777e-08]
 [9.45846565e-07]
 [2.35016507e-04]
 [6.81350883e-13]
 [9.81083406e-10]
 [7.30830044e-13]
 [4.56199065e-03]
 [6.81401680e-11]
 [8

loss at iteration :  40999 [[4.35159184e-14]
 [1.59633330e-05]
 [6.06827139e-09]
 [9.51670776e-07]
 [4.62791224e-12]
 [4.15965854e-09]
 [4.45614306e-06]
 [3.32076050e-11]
 [6.72778306e-04]
 [1.65204587e-06]]
loss at iteration :  41999 [[4.61393998e-01]
 [1.98785448e-17]
 [3.55213888e-06]
 [9.83602254e-18]
 [3.79193390e-05]
 [1.95553627e-14]
 [6.05901092e-03]
 [2.62809695e-13]
 [4.24220858e-10]
 [1.20029756e-06]]
loss at iteration :  42999 [[3.59452273e-07]
 [4.32107452e-04]
 [1.47817060e-04]
 [5.62269912e-06]
 [5.13562550e-06]
 [9.85719183e-06]
 [2.16905009e-05]
 [1.49040371e-06]
 [1.29628929e-04]
 [1.00748348e-07]]
loss at iteration :  43999 [[6.40457071e-09]
 [1.91866974e-13]
 [2.08436005e-08]
 [7.91811237e-10]
 [8.73255222e-05]
 [8.07244746e-06]
 [4.64353623e-08]
 [2.11418141e-06]
 [8.51228864e-05]
 [3.26468450e-03]]
loss at iteration :  44999 [[2.11268513e-07]
 [7.50516028e-09]
 [2.38506626e-09]
 [1.12264583e-08]
 [6.57948984e-18]
 [2.07672810e-07]
 [9.57812513e-13]
 [6.77809630e-1

In [13]:
prediction_list = []
for i in range(X_test.shape[0]): 
    inputs = np.array(X_test[i].reshape(-1,1))
    prediction_list.append(nn.predict(inputs))

correct_counter = 0
for i in range(len(prediction_list)):
    out_index = np.where(prediction_list[i] == np.amax(prediction_list[i]))[0][0]
    
    if y_test[i][out_index] == 1:
        correct_counter+=1

accuracy = correct_counter/num_test

print("Accuracy is : ",accuracy*100," %")

Accuracy is :  96.07  %
